language: python
python: 2.7
sudo: false
cache: pip
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=docs
  - TOXENV=flakes
install:
  - pip install tox
script:
  - tox
