language: python
python: 2.7
sudo: false
cache: pip
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=pypy
  # Don't test this until fixed by travis
  # - TOXENV=pypy3
  - TOXENV=docs
  - TOXENV=lint
install:
  - pip install tox
script:
  - tox
