##-- Travis Build config
##-- Guide for Python projects: http://about.travis-ci.org/docs/user/languages/python/
language: python

##-- which python version(s)
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

install:
 - "pip install -r test_requirements.txt --use-mirrors"

##-- run tests
script: py.test

##-- choose git branches
branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always
