language: python
sudo: false
cache: pip
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  # Don't test this until fixed by travis
  # "pypy3"
install:
  - pip install tox-travis
script:
  - tox
